version: "2"

services:
  db_node_domain:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    env_file: ./envs/env_mysql
    container_name: wordpress_db

  wordpress:
    depends_on: 
      - db_node_domain
    image: wordpress:latest
    expose:
      - 80
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    env_file: ./envs/env_wordpress
    container_name: wordpress
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
