version: "2"

services:
  db_node_domain:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    env_file: ./envs/env_mysql
    container_name: wordpress_db

  wordpress:
    depends_on: 
      - db_node_domain
    image: wordpress:latest
    expose:
      - 80
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      VIRTUAL_HOST: domain
      WORDPRESS_DB_HOST: db_node_domain:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: pass
    container_name: wordpress
volumes:
  db_data:

networks:
  default:
    external:
      name: nginx-proxy
